sheets_config:
  # "2. QBCC - individual":
  #   license_index: 2
  #   status_index: 7
  #   last_checked_index: 9
  # "4.QBCC - Pool Safety Inspectors":
  #   license_index: 2
  #   status_index: 4
  #   last_checked_index: 7
  # "3. QBCC - company":
  #   license_index: 0
  #   status_index: 5
  #   last_checked_index: 7
  # "4. QBCC - certifier":
  #   license_index: 2
  #   status_index: 7
  #   last_checked_index: 9
  "5. Architects":
    license_index: 2
    status_index: 6
    last_checked_index: 7
  "6. Engineers":
    license_index: 2
    status_index: 6
    last_checked_index: 7
numrec_before_save: 15
